[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"

# Netlify Functions settings
[functions]
  node_bundler = "esbuild"

# SPA redirects - QUAN TRỌNG cho React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance headers - CẢI THIỆN TỐC ĐỘ LỚN
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets
    "Cache-Control" = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"
    "Content-Encoding" = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"
    "Content-Encoding" = "gzip"

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    "Cache-Control" = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"

# Netlify-specific optimizations
[context.production.environment]
  NODE_VERSION = "18"

# Enable Netlify's built-in optimizations (ĐÃ FIX SYNTAX)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    audits = [
      "performance",
      "accessibility", 
      "best-practices",
      "seo"
    ]
